// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVZo5ghD8svzpDSU8DPtK1XILvus_LAw',
    appId: '1:1014981934855:web:fe57dc73b166b6e3fc8fa2',
    messagingSenderId: '1014981934855',
    projectId: 'coffe-shope-72bc2',
    authDomain: 'coffe-shope-72bc2.firebaseapp.com',
    storageBucket: 'coffe-shope-72bc2.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVZo5ghD8svzpDSU8DPtK1XILvus_LAw',
    appId: '1:1014981934855:android:fe57dc73b166b6e3fc8fa2',
    messagingSenderId: '1014981934855',
    projectId: 'coffe-shope-72bc2',
    storageBucket: 'coffe-shope-72bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVZo5ghD8svzpDSU8DPtK1XILvus_LAw',
    appId: '1:1014981934855:ios:fe57dc73b166b6e3fc8fa2',
    messagingSenderId: '1014981934855',
    projectId: 'coffe-shope-72bc2',
    storageBucket: 'coffe-shope-72bc2.appspot.com',
    iosClientId:
        '1014981934855-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVZo5ghD8svzpDSU8DPtK1XILvus_LAw',
    appId: '1:1014981934855:ios:fe57dc73b166b6e3fc8fa2',
    messagingSenderId: '1014981934855',
    projectId: 'coffe-shope-72bc2',
    storageBucket: 'coffe-shope-72bc2.appspot.com',
    iosClientId:
        '1014981934855-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVZo5ghD8svzpDSU8DPtK1XILvus_LAw',
    appId: '1:1014981934855:windows:fe57dc73b166b6e3fc8fa2',
    messagingSenderId: '1014981934855',
    projectId: 'coffe-shope-72bc2',
    storageBucket: 'coffe-shope-72bc2.appspot.com',
  );
}
